/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DaysCare.Organization.Classroom;
import DaysCare.Organization.Level;
import DaysCare.SingletonAdmin;
import java.awt.CardLayout;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ViewMain extends javax.swing.JPanel {

    /**
     * Creates new form ViewMain
     */
    JPanel workArea;
    SingletonAdmin admin;
    public ViewMain(JPanel workArea,SingletonAdmin admin) {
        initComponents();
        this.workArea=workArea;
        this.admin=admin;
        populateTable(Level.LEVEL6to12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        cbLevels = new javax.swing.JComboBox<>();

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Class", "Number of Groups", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblClass);

        jLabel1.setText("View Class");

        btnView.setText("View Detail");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        cbLevels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6-12", "13-24", "25-35", "36-47", "48-59", "60+" }));
        cbLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLevelsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLevels, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblClass.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a Classroom");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblClass.getModel();
               Classroom Classroom = (Classroom) model.getValueAt(selectedRowIndex, 0);
               
        ViewClass vm=new ViewClass(workArea,admin,Classroom);
        workArea.add("ViewClass",vm);
        CardLayout layout=(CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewActionPerformed

    private void cbLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLevelsActionPerformed
        // TODO add your handling code here:
        String levelNum=cbLevels.getSelectedItem().toString();
        Level level=checkLevel(levelNum);
        System.out.println(levelNum);
        System.out.println(level);
        populateTable(level);
    }//GEN-LAST:event_cbLevelsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbLevels;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClass;
    // End of variables declaration//GEN-END:variables

    private void populateTable(Level level) {
        List<Classroom>classroomList=admin.getLevelMap().get(level);
        DefaultTableModel model = (DefaultTableModel) tblClass.getModel();
                      model.setRowCount(0);

                      for (Classroom c : classroomList) {
                                 Object[] row = new Object[3];
                                 row[0] = c;
                                 row[1] = c.getGourpList().size();
                                 row[2] = "uncomplete";
                                 model.addRow(row);
                      }
    }
    private Level checkLevel(String s){
        if(s.equals("6-12"))
            return Level.LEVEL6to12;
        else if(s.equals("13-24"))
            return Level.LEVEL13to24;
        else if(s.equals("25-35"))
            return Level.LEVEL25to35;
        else if(s.equals("36-47"))
            return Level.LEVEL36to47;
        else if(s.equals("48-59"))
            return Level.LEVEL48to59;
        else
            return Level.LEVEL60ANDUP;
        
    }
}
